; ===== PlatformIO - DOIT PlayPad Lite =====

[env_base]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
board_build.f_cpu = 240000000L

build_flags =
  -I include
  -I lib/DOITlib
  -D DOIT_LITE
  -D BOTONERA
  -D ADXL
  -D FAST_RF
  -D DEVKIT
  -D NONFC
  -D NOPLAYER
  -D NOMIC

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
  Wire
  FS
  SPIFFS
  fastled/FastLED@3.6.0
  adafruit/Adafruit ADXL345@^1.3.4
  adafruit/Adafruit Unified Sensor@^1.1.15

[env:uart_com13]
extends = env_base
build_type = debug

build_flags =
  ${env_base.build_flags}
  -D BOTONERA_NEW

upload_port = COM13
monitor_port = COM13

debug_init_break = tbreak setup
debug_speed = 40000

[env:usb_native_com4]
extends = env_base
build_type = debug

build_flags =
  ${env_base.build_flags}
  -D BOTONERA_NEW
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

upload_port = COM4
monitor_port = COM4

debug_init_break = tbreak setup
debug_speed = 40000
